language: node_js
node_js:
  - '0.8'
  - '0.11'
  - '0.10'
before_install: "npm install npm && node_modules/.bin/npm install"
script: "npm run test-travis"
after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
